import {
  WidgetType,
  WidgetSize,
  Widget,
} from "@/app/[locale]/dashboard/types/dashboard";
import { DashboardLayoutWithWidgets } from "@/store/user-store";

export const defaultLayouts: DashboardLayoutWithWidgets = {
  id: "",
  userId: "",
  createdAt: new Date(),
  updatedAt: new Date(),
  desktop: [
    // --- ROW 1: KPIs (Top 4 Metrics) ---
    {
      i: "widget_kpi_1",
      type: "cumulativePnl",
      size: "tiny",
      x: 0,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget_kpi_2",
      type: "profitFactor",
      size: "tiny",
      x: 3,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget_kpi_3",
      type: "riskRewardRatio",
      size: "tiny",
      x: 6,
      y: 0,
      w: 3,
      h: 1,
    },
    {
      i: "widget_kpi_4",
      type: "averagePositionTime",
      size: "tiny",
      x: 9,
      y: 0,
      w: 3,
      h: 1,
    },

    // --- ROW 2: Primary Visuals (Charts & Calendar) ---
    {
      i: "widget_main_equity",
      type: "equityChart",
      size: "large",
      x: 0,
      y: 1,
      w: 6,
      h: 8,
    },
    {
      i: "widget_main_calendar",
      type: "calendarWidget",
      size: "large",
      x: 6,
      y: 1,
      w: 6,
      h: 8,
    },

    // --- ROW 3: Detailed Stats & Trends ---
    {
      i: "widget_stats_main",
      type: "statisticsWidget",
      size: "medium",
      x: 0,
      y: 9,
      w: 6,
      h: 4,
    },
    {
      i: "widget_stats_pnl",
      type: "pnlChart",
      size: "medium",
      x: 6,
      y: 9,
      w: 6,
      h: 4,
    },

    // --- ROW 4: Breakdown Analysis (Small Charts) ---
    {
      i: "widget_analysis_weekday",
      type: "weekdayPnlChart",
      size: "small",
      x: 0,
      y: 13,
      w: 3,
      h: 4,
    },
    {
      i: "widget_analysis_timeofday",
      type: "timeOfDayChart",
      size: "small",
      x: 3,
      y: 13,
      w: 3,
      h: 4,
    },
    {
      i: "widget_analysis_side",
      type: "pnlBySideChart",
      size: "small",
      x: 6,
      y: 13,
      w: 3,
      h: 4,
    },
    {
      i: "widget_analysis_distribution",
      type: "tradeDistribution",
      size: "small",
      x: 9,
      y: 13,
      w: 3,
      h: 4,
    },

    // --- ROW 5: Additional Metrics ---
    {
      i: "widget_extra_commissions",
      type: "commissionsPnl",
      size: "small",
      x: 0,
      y: 17,
      w: 3,
      h: 4,
    },
    {
      i: "widget_extra_timeposition",
      type: "timeInPositionChart",
      size: "small",
      x: 3,
      y: 17,
      w: 3,
      h: 4,
    },
    {
      i: "widget_extra_tickdist",
      type: "tickDistribution",
      size: "medium",
      x: 6,
      y: 17,
      w: 6,
      h: 4,
    },
  ],
  mobile: [
    {
      i: "mobile_kpi_pnl",
      type: "cumulativePnl",
      size: "tiny",
      x: 0,
      y: 0,
      w: 12,
      h: 1,
    },
    {
      i: "mobile_main_chart",
      type: "equityChart",
      size: "medium",
      x: 0,
      y: 1,
      w: 12,
      h: 6,
    },
    {
      i: "mobile_main_calendar",
      type: "calendarWidget",
      size: "large",
      x: 0,
      y: 7,
      w: 12,
      h: 6,
    },
    {
      i: "mobile_stats",
      type: "statisticsWidget",
      size: "medium",
      x: 0,
      y: 13,
      w: 12,
      h: 6,
    },
  ],
};