import { getPost } from "@/lib/mdx";
import { notFound } from "next/navigation";
import { Metadata } from "next";
import { getAllPosts, getAdjacentPosts } from "@/lib/mdx";
import { Badge } from "@/components/ui/badge";
import Image from "next/image";
import { format } from "date-fns";
import Script from "next/script";
import { setStaticParamsLocale } from "next-international/server";
import { getStaticParams as getLocaleStaticParams } from "@/locales/server";
import { MdxSidebar } from "@/components/mdx-sidebar";
import { UpdatesNavigation } from "@/components/updates-navigation";

interface PageProps {
  params: Promise<{
    slug: string;
    locale: string;
  }>;
}

// export const dynamic = "force-static"; // Allow Next.js to auto-optimize
export const dynamicParams = true; // Allow new posts without rebuilding
export const revalidate = 3600;

// Generate static paths for all posts in all locales
export async function generateStaticParams() {
  const locales = getLocaleStaticParams().map((entry) => entry.locale);
  const paths: Array<{ locale: string; slug: string }> = [];

  for (const locale of locales) {
    const posts = await getAllPosts(locale);
    paths.push(
      ...posts.map((post) => ({
        locale,
        slug: post.slug,
      }))
    );
  }

  return paths;
}

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  try {
    const resolvedParams = await params;
    if (!resolvedParams || !resolvedParams.slug || !resolvedParams.locale) {
      return {
        title: "Not Found",
        description: "The page you are looking for does not exist.",
      };
    }

    const { slug, locale } = resolvedParams;
    setStaticParamsLocale(locale);

    try {
      const post = await getPost(slug, locale);
      if (!post)
        return {
          title: "Not Found",
          description: "The page you are looking for does not exist.",
        };
      const { meta } = post;

      const url = `https://quntedge.com/${locale}/updates/${slug}`;

      return {
        title: meta.title,
        description: meta.description,
        alternates: {
          canonical: url,
          languages: {
            en: `https://quntedge.com/en/updates/${slug}`,
            fr: `https://quntedge.com/fr/updates/${slug}`,
          },
        },
        openGraph: {
          title: meta.title,
          description: meta.description,
          type: "article",
          publishedTime: meta.date,
          modifiedTime: meta.updatedAt || meta.date,
          url,
          siteName: "Delatlytix",
          locale: locale,
          // images are automatically generated by opengraph-image.tsx
        },
        twitter: {
          card: "summary_large_image",
          title: meta.title,
          description: meta.description,
          // images are automatically generated by opengraph-image.tsx
        },
      };
    } catch (postError) {
      console.error("Error fetching post:", postError);
      return {
        title: "Not Found",
        description: "The page you are looking for does not exist.",
      };
    }
  } catch (paramError) {
    console.error("Error resolving params:", paramError);
    return {
      title: "Not Found",
      description: "The page you are looking for does not exist.",
    };
  }
}

async function getPageData(slug: string, locale: string) {
  try {
    const post = await getPost(slug, locale);
    if (!post) {
      return null;
    }

    const adjacent = await getAdjacentPosts(slug, locale);
    return {
      post,
      previous: adjacent.previous,
      next: adjacent.next,
    };
  } catch (postError) {
    console.error("Error fetching post data:", postError);
    return null;
  }
}

export default async function Page({ params }: PageProps) {
  const resolvedParams = await params;
  if (!resolvedParams || !resolvedParams.slug || !resolvedParams.locale) {
    notFound();
  }

  const { slug, locale } = resolvedParams;
  setStaticParamsLocale(locale);

  const pageData = await getPageData(slug, locale);
  if (!pageData) {
    notFound();
  }

  const { post, previous, next } = pageData;
  const { meta, content } = post;
  const formattedDate = format(new Date(meta.date), "MMMM d, yyyy");
  const url = `https://qunt-edge.vercel.app/${locale}/updates/${slug}`;

  // Prepare JSON-LD structured data
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: meta.title,
    description: meta.description,
    image: meta.image || "/og-image.png",
    datePublished: meta.date,
    dateModified: meta.updatedAt || meta.date,
    author: {
      "@type": "Organization",
      name: "Delatlytix",
      url: "https://qunt-edge.vercel.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Delatlytix",
      logo: {
        "@type": "ImageObject",
        url: "https://qunt-edge.vercel.app/logo.png",
      },
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": url,
    },
  };

  return (
    <>
      <Script id="json-ld" type="application/ld+json">
        {JSON.stringify(jsonLd)}
      </Script>

      <article
        className="w-full px-4 pt-16 pb-16 sm:px-6 lg:px-8"
        itemScope
        itemType="https://schema.org/Article"
      >
        <UpdatesNavigation
          previous={previous}
          next={next}
          locale={locale}
          position="top"
        />
        <div className="mb-8">
          <div className="flex items-center gap-4 text-sm text-muted-foreground/70 dark:text-muted-foreground/50 mb-4">
            <time dateTime={meta.date} itemProp="datePublished">
              {formattedDate}
            </time>
            <Badge
              variant={
                meta.status === "in-progress"
                  ? "secondary"
                  : meta.status === "completed"
                    ? "default"
                    : "outline"
              }
            >
              {meta.status === "in-progress"
                ? "In Progress"
                : meta.status === "completed"
                  ? "Completed"
                  : "Upcoming"}
            </Badge>
          </div>
        </div>

        {meta.image && (
          <div className="mb-8 rounded-lg overflow-hidden bg-card/70 dark:bg-card/80">
            <Image
              src={meta.image}
              alt={meta.title}
              width={1200}
              height={600}
              className="w-full h-auto"
              priority
              itemProp="image"
            />
          </div>
        )}

        <div
          className="prose dark:prose-invert max-w-none 
          prose-pre:p-0 prose-pre:bg-transparent 
          prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-code:bg-card/70 prose-code:text-muted-foreground
          dark:prose-code:bg-card/90 dark:prose-code:text-muted-foreground/80
          prose-table:w-full prose-table:mt-6 prose-table:mb-8
          prose-thead:border-b prose-thead:border-border/60 dark:prose-thead:border-border/80
          prose-th:px-6 prose-th:py-3 prose-th:text-left prose-th:font-semibold
          prose-td:px-6 prose-td:py-3 prose-td:border-b prose-td:border-border/60 dark:prose-td:border-border/80
          prose-tr:transition-colors prose-tr:hover:bg-card/80 dark:prose-tr:hover:bg-card/90"
          itemProp="articleBody"
        >
          {content}
        </div>
        <UpdatesNavigation
          previous={previous}
          next={next}
          locale={locale}
        />
        <MdxSidebar />
      </article>
    </>
  );
}
